# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c7c47d66f5b0509b468c32b1a8688dc3da0100493be5d24b283424f77da8ea85f313b0c49c257710f5b28a62cf9668de9ee116878c10b99266fdd857ebc7edc1

test:
  secret_key_base: e0d7005e870812d22b814327ba2e5e9628ecdf22d6fe070190072fb6a899ef7c3f6caca50fb76b3ef355f36ef4850ea4f5a920f3fd54868506ab8cc56ddd5270

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
